server:
  port: ${APPLICATION_SERVER_PORT:8082}

spring:
  data:
    # properties for mongodb
    mongodb:
      host: ${MONGODB_SERVER_ADDRESS:localhost}
      port: ${MONGODB_PORT_ADDRESS:27017}
      database: ${MONGODB_DATABASE_NAME:jobs}

  # spring.kafka.bootstrap-servers specifies the address of your Kafka broker, and spring.kafka.consumer.group-id specifies the consumer group ID for your application
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_ADDRESS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:jobs-consumer-group-1}
      topic: ${KAFKA_CONSUMER_TOPIC_ID:jobs-topic-id-1}
    producer:
      topic: ${KAFKA_PRODUCER_TOPIC_ID:jobs-topic-id-1}

clockwork:
  repetition-time-unit: 120000